### ISSUE TITLE
[BUG] [SM] Deploy Phase 0 fails with "A PolicyStatement used in a resource-based policy must specify at least one IAM principal"

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-secure-environment-accelerator#1006]
**Required Basic Info**
- Accelerator Version:  v1.1.5-a
- Install Type: Clean with many re-runs. Some config errors and then limit issues.
- Upgrade from version: N/A
- State Machine Fail in: Deploy Phase 0

**Describe the bug**
```


Total stacks = 12
--
58 | deploying stack 1 of 12
59 | deploying stack 2 of 12
60 | deploying stack 3 of 12
61 | deploying stack 4 of 12
62 | deploying stack 5 of 12
63 | deploying stack 6 of 12
64 | deploying stack 7 of 12
65 | deploying stack 8 of 12
66 | deploying stack 9 of 12
67 | deploying stack 10 of 12
68 | deploying stack 11 of 12
69 | deploying stack 12 of 12
70 | Error: Validation failed with the following errors:
71 | [ManagementPhase0/Secrets/EncryptionKey] A PolicyStatement used in a resource-based policy must specify at least one IAM principal.
72 | at validateTree (/app/node_modules/.pnpm/@aws-cdk+core@1.144.0/node_modules/@aws-cdk/core/lib/private/synthesis.ts:213:11)
73 | at Object.synthesize (/app/node_modules/.pnpm/@aws-cdk+core@1.144.0/node_modules/@aws-cdk/core/lib/private/synthesis.ts:28:5)
74 | at AccountApp.synth (/app/node_modules/.pnpm/@aws-cdk+core@1.144.0/node_modules/@aws-cdk/core/lib/stage.ts:94:23)
75 | at /app/src/deployments/cdk/toolkit.ts:83:44
76 | at Array.map (<anonymous>)
77 | at Function.create (/app/src/deployments/cdk/toolkit.ts:83:29)
78 | at main (/app/src/deployments/cdk/cdk.ts:104:40)
79 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
[Container] 2022/07/11 14:16:22 Command did not exit successfully sh docker-entrypoint.sh exit status 1
82 | [Container] 2022/07/11 14:16:22 Phase complete: BUILD State: FAILED
83 | [Container] 2022/07/11 14:16:22 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sh docker-entrypoint.sh. Reason: exit status 1
84 | [Container] 2022/07/11 14:16:22 Entering phase POST_BUILD
85 | [Container] 2022/07/11 14:16:22 Running command buildComplete=`cat /tmp/buildStatus.txt`
86 |  
87 | [Container] 2022/07/11 14:16:22 Running command if [ $buildComplete = "complete" ]; then echo "Build Finished"; else echo "Build did not finish. please review logs for errors!" && exit 1; fi
88 | Build did not finish. please review logs for errors!
89
```

**Failure Info**
- What error messages have you identified, if any: 
- What symptoms have you identified, if any:

**Required files**
- Please provide a copy of your config.json file (sanitize if required)
- If a CodeBuild step failed- please provide the full CodeBuild Log
- If a Lambda step failed - please provide the full Lambda CloudWatch Log
- In many cases it would be helpful if you went into the failed sub-account and region, CloudFormation, and provided a screenshot of the Events section of the failed, deleted, or rolled back stack including the last successful item, including the first couple of error messages (bottom up)

**Steps To Reproduce**
1. using config.ultralite-example.json
2. run

**Expected behavior**
Phase to complete successfully

**Screenshots**

**Additional context**

**Comment by kbroughton** [comment]
This was a config change issue, but the fix might be mentioned in the documentation.
Initially, the user-ids are ["User1", "User2"]. I changed it to a personal user I'd created
for bootstrapping. This fails because ASEA complains the user is already created.
Deleting all user-ids yields the error above.
```
  "mandatory-account-configs": {
    "management": {
      "account-name": "management-org",
      "iam": {
        "users": [
          {
            "user-ids": ["User1", "User2"],
            "group": "BreakGlassAdmins",
            "policies": ["AdministratorAccess"],
            "boundary-policy": "Default-Boundary-Policy"
          }
        ],
```

So the suggestion would be to call out the need to change the user to a name that does not already exist.

**Comment by kbroughton** [comment]
config issue, possibly documentation
