### ISSUE TITLE
Failed Upgrade from v1.5.5 to version 1.5.6a

### ISSUE THREAD

**Issue by mtaki22** [aws-samples/aws-secure-environment-accelerator#1146]
Upgrade failed from v1.5.5 to v1.5.6a
The customer did the changes related to Flow Logs.
Machine state failed after several retries. 
Logs from CodeBuild logs.

"xx,{""""stackName"""":""""OperationsPhase3ApSouth_1 (ASEA-Operations-Phase3)"""",""""stackEnvironment"""":{""""account"""":""""xx"""",""""region"""":""""ap-south-1"""",""""name"""":""""aws://xx/ap-south-1""""},""""assumeRoleArn"""":""""arn:aws:iam::xx:role/ASEA-PipelineRole"""",""""message"""":""""Deleted assembly directory"""",""""messageType"""":""""INFO""""}"
"
xx,Error: TypeError: Cannot read property 'includes' of undefined"
"
xx,    at Object.fulfillAll (/app/src/deployments/cdk/promise.ts:8:11)"
"
xx,    at CdkToolkit.deployAllStacks (/app/src/deployments/cdk/toolkit.ts:192:27)"
"
xx,    at main (/app/src/deployments/cdk/cdk.ts:115:9)"
"
xx,"
"
xx,[Container] 2023/04/21 19:32:07 Command did not exit successfully sh docker-entrypoint.sh exit status 1"
"
xx,[Container] 2023/04/21 19:32:07 Phase complete: BUILD State: FAILED"
"
xx,[Container] 2023/04/21 19:32:07 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sh docker-entrypoint.sh. Reason: exit status 1"
"
xx,[Container] 2023/04/21 19:32:07 Entering phase POST_BUILD"
"
xx,[Container] 2023/04/21 19:32:07 Running command buildComplete=`cat /tmp/buildStatus.txt`"
"
xx,"
"
xx,[Container] 2023/04/21 19:32:07 Running command if [ $buildComplete = """"complete"""" ]"
"
xx,Build did not finish. please review logs for errors!"
"
xx,"
"
xx,[Container] 2023/04/21 19:32:07 Command did not exit successfully if [ $buildComplete = """"complete"""" ]"
"
xx,[Container] 2023/04/21 19:32:07 Phase complete: POST_BUILD State: FAILED"
"
xx,[Container] 2023/04/21 19:32:07 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ $buildComplete = """"complete"""" ]"

**Comment by mtaki22** [comment]
The customer managed to upgrade successfully. It seems that  since initially they missed the step of changing the flow-logs, the state machine kept failing even after correcting the flow-logs step. The steps taken by the customer to revert to v1.5.5 then re-initiate the upgrade steps correctly solved the issue.
