### ISSUE TITLE
[BUG] [SM] Zones - when no zones deployed, must provide account and vpc or SM fails

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#523]
**Required Basic Info**
- Accelerator Version:  v1.2.3
- Install Type: All
- Install Branch: Standalone
- Upgrade from version: N/A
- Which State did the Main State Machine Fail in: Phase 1

**Describe the bug**
While we can deploy no zones by leaving the public and private arrays empty, if we remove all zone entries from the array, SM fails.  Currently we require an account with a VPC, even if we don't deploy the zones.

Works:
```
    "zones": [
      {
        "account": "shared-network",
        "resolver-vpc": "Endpoint",
        "region": "ca-central-1",
        "names": {
          "public": [],
          "private": []
        }
      }
    ], 
```

Fails:
```
    "zones": [    ], 
```

**Failure Info**
- What error messages have you identified, if any: 
  - Phase 1 Codebuild:
```
Cannot find account with key "undefined"
Error: Cannot find account stack for account undefined
```

**Expected behavior**
If we are not deploying any zones, we should not need to provide an account name or a VPC name.

**NOTE**
- Something else is wrong in the codebase - changing the zones account breaks other R53 functionality like resolver rules, which should be completely unrelated.  If we deploy NO ZONES, but point the ZONES at a different account/vpc
- (I should have caught it , under zones, the variable is "resolver-vpc", when it should just be vpc - zone vpc's have nothing to do with resolver vpc's)
- resolver endpoints and resolver rules appear to no longer exist, 
- the resolver security groups have issues creating - CREATE_FAILED        | AWS::EC2::SecurityGroup                | SharedNetworkPhase3ResolverEndpoints_1/ResolverEndpoints-shared-network-Endpoint/OutboundSecurityGroup (ResolverEndpointssharednetworkEndpointOutboundSecurityGroupEAD27F10) Endpoint_outbound_endpoint_sg already exists in stack arn:aws:cloudformation:ca-central-1:642462841348:stack/PBMMAccel-SharedNetwork-Phase3-CentralVpcResolverEndpoints/2f76b8a0-0d70-11eb-a466-063829308218

**Comment by Brian969** [comment]
- Succeeds during an upgrade using an ultralite config file
- Failed during an upgrade using a standard config file in "Phase -1 Outputs" - "ERROR	Invoke Error"
- "central-endpoint": true on endpoint VPC, old zones section removed from config file
```
{
    "errorType": "Error",
    "errorMessage": "Unable to load configuration file \"raw/config.json\" in Repository PBMMAccel-Config-Repo\nCould not parse content:\n* Invalid value undefined supplied to /global-options/zones",
    "stack": [
        "Error: Unable to load configuration file \"raw/config.json\" in Repository PBMMAccel-Config-Repo",
        "Could not parse content:",
        "* Invalid value undefined supplied to /global-options/zones",
        "    at ft (/var/task/index.js:263:183056)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "    at async Runtime.wi [as handler] (/var/task/index.js:263:269616)"
    ]
}
```

**Comment by Brian969** [comment]
Shipping in v1.2.4
