### ISSUE TITLE
[BUG] [SM] SM fails with an ultra lite configuration w/single IAM policy definition

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#533]
(already fixed, opening ticket for record keeping).

**Required Basic Info**
- Accelerator Version:  v1.2.3
- Install Type: ALL
- Install Branch: ALL
- Upgrade from version: N/A
- Which State did the Main State Machine Fail in: Phase 1

**Describe the bug**
We found an issue when creating an ultra-lite configuration, when a policy file is used by multiple accounts, we require the policy to be referenced multiple times in any one account or the SM fails.

**Failure Info**
- What error messages have you identified, if any: 
```
SyntaxError: Unexpected token u in JSON at position 0, 
    at JSON.parse (<anonymous>)
    at createIamPolicy (/app/src/deployments/cdk/src/common/iam-assets.ts:33:34)
   at new IamAssets (/app/src/deployments/cdk/src/common/iam-assets.ts:174:11)
   at createIamAssets (/app/src/deployments/cdk/src/apps/phase-1.ts:361:25)
    at deploy (/app/src/deployments/cdk/src/apps/phase-1.ts:386:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deploy (/app/src/deployments/cdk/src/app.ts:70:3)
    at main (/app/src/deployments/cdk/cdk.ts:36:16)
```
Using an ultra-light config with most things stripped out. 

**Expected behavior**
SM fails

**Comment by Brian969** [comment]
Shipping in v1.2.4
