### ISSUE TITLE
[BUG] [SM] Suspended accounts still causing issues

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#613]
**Required Basic Info**
- Accelerator Version:  v1.2.4
- Install Type: ANY
- Which State did the Main State Machine Fail in: Compare

**Describe the bug**
- suspend an aws account through AWS orgs
- which auto-triggers moving the account to the suspended ou and adding delete=true to the config file
- the next state machine fails, EVEN IN WORKLOAD ACCOUNTS, because the ou comparison fails

**Failure Info**
In this case, it’s a workload config and I’ve verified that the first SM run worked properly, it added the deleted flag and completed.  I double checked and the the account is in the suspended OU.   I then ran the SM without the flag (since it’s not a mandatory account):

{
    "errorType": "Error",
    "errorMessage": "There were errors while comparing the configuration changes:\nConfigCheck: blocked changing ou from config path \"workload-account-configs/ABC-Onboard-Dev/ou\"",
    "stack": [
        "Error: There were errors while comparing the configuration changes:",
        "ConfigCheck: blocked changing ou from config path \"workload-account-configs/ABC-Onboard-Dev/ou\"",
        "    at Runtime.oi [as handler] (/var/task/index.js:263:253624)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}

**Expected behavior**
- the delete=true flag is supposed to bypass the ou change validation check
- we were aware it did not bypass the validation check for mandatory accounts, but it was stated as working for workload accounts
- as we need to fix this for workload accounts, please also fix for mandatory accounts too

**Comment by Brian969** [comment]
Can't find the customer reported issue after numerous tests.  We did discover an issue if accounts are removed from the Org, which has been corrected in PR618.

**Comment by Brian969** [comment]
- This will ship in v1.2.6
