### ISSUE TITLE
[BUG][PIPELINE] Pipeline does not include stack cleanup, like SM does

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#641]
**Required Basic Info**
- Accelerator Version:  Pre v1.3.0, before v1.2.6-a patch
- Install Type: Clean
- CodePipeline failure in "Deploy" step does not cleanup stacks

**Describe the bug**
BUG1:
- When the "Deploy" phase fails - it leaves stacks in Rollback Complete status, rather than cleaning up stacks, like we do in the state machine
- Add code to properly cleanup stacks

BUG2:
- cdk deploy breaks when qualifier is used

**Failure Info**
- will add as a separate comment

**Comment by Brian969** [comment]
Here’s the logs from that run:
```
[Container] 2021/02/26 09:21:53 Running command pnpx cdk bootstrap aws://XXXXXXXXXXXX/us-east-1 --require-approval never --toolkit-stack-name=CombinedAccel-CDKToolkit --cloudformation-execution-policies=arn:aws:iam::aws:policy/AdministratorAccess 
CDK_NEW_BOOTSTRAP set, using new-style bootstrapping 
Installing Accelerator with version: 1.2.6-a 
Found accelerator context: 
Name: Combined 
Prefix: CombinedAccel- 
Bootstrapping environment aws://XXXXXXXXXXXX/us-east-1... 
Trusted accounts: (none) 
Execution policies: arn:aws:iam::aws:policy/AdministratorAccess 
CombinedAccel-CDKToolkit: creating CloudFormation changeset... 
0/11 | 9:22:08 AM | REVIEW_IN_PROGRESS | AWS::CloudFormation::Stack | CombinedAccel-CDKToolkit User Initiated 
0/11 | 9:22:13 AM | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | CombinedAccel-CDKToolkit User Initiated 
0/11 | 9:22:19 AM | CREATE_IN_PROGRESS | AWS::ECR::Repository | ContainerAssetsRepository 
0/11 | 9:22:19 AM | CREATE_IN_PROGRESS | AWS::IAM::Role | CloudFormationExecutionRole 
0/11 | 9:22:19 AM | CREATE_IN_PROGRESS | AWS::SSM::Parameter | CdkBootstrapVersion 
0/11 | 9:22:19 AM | CREATE_IN_PROGRESS | AWS::IAM::Role | FilePublishingRole 
0/11 | 9:22:19 AM | CREATE_IN_PROGRESS | AWS::S3::Bucket | StagingBucket 
0/11 | 9:22:19 AM | CREATE_IN_PROGRESS | AWS::IAM::Role | ImagePublishingRole 
0/11 | 9:22:20 AM | CREATE_IN_PROGRESS | AWS::IAM::Role | CloudFormationExecutionRole Resource creation Initiated 
0/11 | 9:22:20 AM | CREATE_IN_PROGRESS | AWS::IAM::Role | ImagePublishingRole Resource creation Initiated 
0/11 | 9:22:20 AM | CREATE_IN_PROGRESS | AWS::IAM::Role | FilePublishingRole Resource creation Initiated 
0/11 | 9:22:20 AM | CREATE_FAILED | AWS::S3::Bucket | StagingBucket cdk-hnb659fds-assets-XXXXXXXXXXXX-us-east-1 already exists 
0/11 | 9:22:21 AM | CREATE_FAILED | AWS::IAM::Role | FilePublishingRole Resource creation cancelled 
0/11 | 9:22:21 AM | CREATE_FAILED | AWS::IAM::Role | CloudFormationExecutionRole Resource creation cancelled 
0/11 | 9:22:21 AM | CREATE_FAILED | AWS::IAM::Role | ImagePublishingRole Resource creation cancelled 
0/11 | 9:22:21 AM | CREATE_FAILED | AWS::SSM::Parameter | CdkBootstrapVersion Resource creation cancelled 
0/11 | 9:22:22 AM | CREATE_FAILED | AWS::ECR::Repository | ContainerAssetsRepository Resource creation cancelled 
0/11 | 9:22:22 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | CombinedAccel-CDKToolkit The following resource(s) failed to create: [ImagePublishingRole, FilePublishingRole, CdkBootstrapVersion, StagingBucket, CloudFormationExecutionRole, ContainerAssetsRepository]. Rollback requested by user. 
0/11 | 9:22:37 AM | DELETE_IN_PROGRESS | AWS::IAM::Role | ImagePublishingRole 
0/11 | 9:22:37 AM | DELETE_IN_PROGRESS | AWS::IAM::Role | CloudFormationExecutionRole 
0/11 | 9:22:37 AM | DELETE_IN_PROGRESS | AWS::SSM::Parameter | CdkBootstrapVersion 
0/11 | 9:22:37 AM | DELETE_IN_PROGRESS | AWS::ECR::Repository | ContainerAssetsRepository 
0/11 | 9:22:38 AM | DELETE_SKIPPED | AWS::S3::Bucket | StagingBucket 
0/11 | 9:22:38 AM | DELETE_IN_PROGRESS | AWS::IAM::Role | FilePublishingRole 
6/11 | 9:22:39 AM | DELETE_COMPLETE | AWS::IAM::Role | ImagePublishingRole 
6/11 | 9:22:39 AM | DELETE_COMPLETE | AWS::ECR::Repository | ContainerAssetsRepository 
6/11 | 9:22:39 AM | DELETE_COMPLETE | AWS::IAM::Role | FilePublishingRole 
6/11 | 9:22:39 AM | DELETE_COMPLETE | AWS::IAM::Role | CloudFormationExecutionRole 
6/11 | 9:22:40 AM | DELETE_COMPLETE | AWS::SSM::Parameter | CdkBootstrapVersion 
6/11 | 9:22:41 AM | ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | CombinedAccel-CDKToolkit 
-------------------------------------------------------------------------------------------------------
❌ Environment aws://XXXXXXXXXXXX/us-east-1 failed bootstrapping: Error: The stack named CombinedAccel-CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE 
at Object.waitForStackDeploy (/codebuild/output/src666392671/src/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/api/util/cloudformation.ts:305:11) 
at processTicksAndRejections (internal/process/task_queues.js:97:5) 
at Object.deployStack (/codebuild/output/src666392671/src/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/api/deploy-stack.ts:283:26) 
at /codebuild/output/src666392671/src/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/cdk-toolkit.ts:361:24 
at async Promise.all (index 0) 
at CdkToolkit.bootstrap (/codebuild/output/src666392671/src/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/cdk-toolkit.ts:358:5) 
at initCommandLine (/codebuild/output/src666392671/src/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/bin/cdk.ts:202:9) 
The stack named CombinedAccel-CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE 
-------------------------------------------------------------------------------------------------------
[Container] 2021/02/26 09:22:44 Command did not exit successfully pnpx cdk bootstrap aws://XXXXXXXXXXXX/us-east-1 --require-approval never --toolkit-stack-name=CombinedAccel-CDKToolkit --cloudformation-execution-policies=arn:aws:iam::aws:policy/AdministratorAccess exit status 1 
[Container] 2021/02/26 09:22:44 Phase complete: BUILD State: FAILED 
[Container] 2021/02/26 09:22:44 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: pnpx cdk bootstrap aws://XXXXXXXXXXXX/us-east-1 --require-approval never --toolkit-stack-name=CombinedAccel-CDKToolkit --cloudformation-execution-policies=arn:aws:iam::aws:policy/AdministratorAccess. Reason: exit status 1 
[Container] 2021/02/26 09:22:44 Entering phase POST_BUILD 
[Container] 2021/02/26 09:22:44 Phase complete: POST_BUILD State: SUCCEEDED 
[Container] 2021/02/26
```

**Comment by naveenkoppula** [comment]
Did raise a bug in CDK with respect to using acceleratorPrefix as a qualifier

https://github.com/aws/aws-cdk/issues/13358

**Comment by Brian969** [comment]
Latest CDK issue report: https://github.com/aws/aws-cdk/issues/14701

**Comment by Brian969** [comment]
Closing due to lack of response from CDK team.
