### ISSUE TITLE
[BUG][OTHER] Pnpm install is failing

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#671]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version: 1.3.0

**Describe the bug**
Throwing exception 
```
.../cdk-cfn-sleep/runtime prepare$ webpack-cli --config webpack.config.ts
│ Executing pre-build scripts
│ Hash: c3e7696e28833bf7b650
│ Version: webpack 4.42.1
│ Time: 535ms
│ Built at: 03/26/2021 7:17:19 PM
│    Asset      Size  Chunks             Chunk Names
│ index.js  10.6 KiB       0  [emitted]  main
│ Entrypoint main = index.js
│ [1] ./src/index.ts 1.05 KiB {0} [built]
│ [2] /Users/rverma/dev/diff/pbmm/src/lib/custom-resources/runtime-cfn-response/src/index.ts 3.23 KiB {0} [built]
│ [3] external "https" 42 bytes {0} [built]
│ [4] external "url" 42 bytes {0} [built]
│     + 9 hidden modules
│ ../../../../../node_modules/.pnpm/@types/tapable@2.2.0/node_modules/@types/tapable/index.d.ts(7,15): error TS2307: Cannot find module './node_modules/tapable'.
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(30,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(31,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(32,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(33,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(34,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(35,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(36,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(37,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(38,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(39,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ ../../../../../node_modules/.pnpm/@types/webpack@4.41.8/node_modules/@types/webpack/index.d.ts(40,3): error TS2305: Module '"../../../../../../../../../../../../Users/rverma/dev/diff/pbmm/node_modules
│ Error: Command failed: tsc --declaration --emitDeclarationOnly --outDir /Users/rverma/dev/diff/pbmm/src/lib/custom-resources/cdk-cfn-sleep/runtime/dist
│     at ChildProcess.exithandler (child_process.js:308:12)
│     at ChildProcess.emit (events.js:315:20)
│     at maybeClose (internal/child_process.js:1048:16)
│     at Socket.<anonymous> (internal/child_process.js:439:11)
│     at Socket.emit (events.js:315:20)
│     at Pipe.<anonymous> (net.js:673:12)
└─ Failed in 7.5s
```

**Comment by rverma-nsl** [comment]
By the way, did it ever cross your mind to use dependabot https://github.com/dependabot ?
