### ISSUE TITLE
[BUG][Functional] VPC creation and related resources (Route table, Subnets) failes when workload account label doesn't start with a letter

### ISSUE THREAD

**Issue by jblaplace** [aws-samples/aws-secure-environment-accelerator#972]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  1.5.0
- Install Type: (Clean or Upgrade) Upgrade
- Upgrade from version: (N/A or v1.x.y): 1.3.x

**Describe the bug**
VPC creation and related resources (Route table, Subnets) failes when workload account label doesn't start with a letter.
CodeBuild fails with Deploy Phase 1.

**Failure Info**
Error: Resolution error: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got '0096AuthgouvCentralPhase1VpcStackAuthgouvCentralauthgouvCentralCD4FB26FRef'.

Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces
  at validateLogicalId (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/private/logical-id.ts:79:11)
  at LogicalIDs.applyRename (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/private/logical-id.ts:48:5)
  at VpcStack.getLogicalId (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/stack.ts:266:29)
  at CfnOutput.synthesizeLogicalId (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/cfn-element.ts:100:25)
  at Object.produce (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/cfn-element.ts:37:64)
  at LazyString.resolve (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/lazy.ts:167:28)
  at DefaultTokenResolver.resolveToken (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/resolvable.ts:80:24)
  at resolve (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/private/resolve.ts:212:51)
  at Object.resolve [as mapToken] (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/private/resolve.ts:119:77)
  at TokenizedStringFragments.mapTokens (/app/node_modules/.pnpm/@aws-cdk+core@1.113.0/node_modules/@aws-cdk/core/lib/string-fragments.ts:65:33)

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
1. Create an account with a account-name and 'account label' starting is a number ex:  "0096-authgouv-central": {
            "account-name": "0096-authgouv-central",
2. Deploy via config.json a local VPC within the account
3. See error above

**Expected behavior**
The VPC and its subnets should deploy.

**Screenshots**

**Additional context**

**Comment by Brian969** [comment]
@jblaplace - what is the name of the VPC and subnet in the above situation?  Thxs.

**Comment by jblaplace** [comment]
i'll email you the config in a moment.
The vpc name was: authgouvCentral
The subnets were  Web and  App
