### ISSUE TITLE
[BUG] [SM] 

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-secure-environment-accelerator#985]
**Required Basic Info**
* Accelerator Version: v1.5.1-a
* troubleshooting initial run
* Load Accounts
* config.json based on reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json

**Describe the bug**
The error message says SharedNetwork account was not created. However, I would expect that that account would be created by the StateMachine.
Using the AWS Organizations page I can see that the SharedNetwork account was created under the Infrastructure OU, but like the other accounts it is in a "suspended" state. 

**Failure Info**
```
{
  "errorType": "Error",
  "errorMessage": "Cannot find account with name \"SharedNetwork\" and email \"wsaws+aseaT-network@example.com\"",
  "trace": [
    "Error: Cannot find account with name \"SharedNetwork\" and email \"wsaws+aseaT-network@example.com\"",
    "    at Runtime.Q40 [as handler] (/var/task/index.js:1374:27256)",
    "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  ]
}
```
 

**Required files**
- I don't see an upload file button anymore for the config.json upload

**Steps To Reproduce**
* Create a brand new account. Make it an Org. Follow all the steps in https://catalog.us-east-1.prod.workshops.aws/workshops/f3ed5d0f-d2f1-47e8-a305-168da9179aaa/en-US/sea-administrators
to setup the org and root account.
* Upload the config.json file to an S3 bucket
* Launch the AWSA CF template using latest release

**Expected behavior**
State machine does not fail

There should not be extra preparation steps not mentioned in the workshop for admins docs:
https://catalog.us-east-1.prod.workshops.aws/workshops/f3ed5d0f-d2f1-47e8-a305-168da9179aaa/en-US/sea-administrators

State-machine should create the SharedNetwork account/VPC

Account should be "available" or StateMachine should notify admin that the account state is pending, include instructions on how to fix this, and slowly poll until it is available.

**Screenshots**

**Additional context**

Might be tangentially related to https://github.com/aws-samples/aws-secure-environment-accelerator/issues/523

**Comment by Brian969** [comment]
Hi,
I've never seen an account flip to suspended status during account creation.  The account creation API [returns](https://docs.aws.amazon.com/cli/latest/reference/organizations/list-create-account-status.html) "In Progress", Failed", or " Succeeded.  We do create all the accounts and wait for all newly created accounts to flip from In-Progress to Succeeded / an Active status.  We do also automatically skip [Suspended](https://docs.aws.amazon.com/organizations/latest/APIReference/API_Account.html) accounts.  If an account is suspended, it requires manual intervention to re-open and is beyond the scope of anything we can handle in code.  Please open an AWS support case to determine why your account was suspended (and only they can [unsuspend](https://aws.amazon.com/premiumsupport/knowledge-center/reactivate-suspended-account/) it).

Love it if you would report back as to the root cause of the accounts flipping to suspended status.

The only thing I can think of is you exceeded your "[Default maximum number of accounts]" Service Quota for AWS Organizations (Can only be checked in us-east-1), but this would be new behavior - previously the API call would have failed with an Account Limit exceeded error.

**Comment by kbroughton** [comment]
It appears AWS was not happy with us using team names for the Account which did not match the name on the Credit card. That's my best guess. After  70 hours the suspension was lifted, but we were not told what the root problem was.

Now the accounts dot now show the "Suspended" state, however, there is still an SCP policy AWS-QuarrantineNewObject
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "DenyAllAWSServicesExceptBreakglassRoles",
      "Effect": "Deny",
      "Action": "*",
      "Resource": "*",
      "Condition": {
        "ArnNotLike": {
          "aws:PrincipalARN": [
            "arn:aws:iam::*:role/OrganizationAccountAccessRole",
            "arn:aws:iam::*:role/ASEA-*",
            "arn:aws:iam::*:role/aws*"
          ]
        }
      }
    }
  ]
}
```
And I cannot delete this policy because it says it is still in use.

The state machine now runs to the "DeleteDefaultVpcs" step where it fails without much info.
I went to the root account's VCP and discovered there were a few items left, but I deleted everything and it still fails at that step. So not sure if i'm still missing something or if it's the lingering SCP policy.

 
![Screen Shot 2022-05-31 at 1 55 20 PM](https://user-images.githubusercontent.com/10562482/171267523-2b3ed83f-dfaf-4e0e-bad6-5c0fd1314eca.png)

I've not touched any of the member accounts, so I presume it's not failing there, but I can't login to debug as the user account for cross-account roles i created does not satisfy the Quarantine SCP.

**Comment by Brian969** [comment]
Hi,
- The logs should indicate which account and region has something blocking deleting the default VPC.
  - in the above screenshot - under VPC - select ```see all regions``` and you should see which region has a remaining default VPC (if its the root account)
  - go to that region an manually delete the VPC.  While the GUI will ask you if you want to delete all the "stray objects" associated with the VPC - we abort if customer objects exist - this can include a simple security group.
  - if its a sub-account, you need to go into the sub-account - you can assume the ```ASEA-PipelineRole``` from the root/mgmt account to fix it up. 
- The SCP remains attached until the SM succeeds to prevent an account from being used before all guardrails are properly applied.

**Comment by kbroughton** [comment]
Thanks for that.
Using all regions, I deleted 7 other VPCs and that fixed it.
I was in the mgmt account.

This issue is resolved.
