### ISSUE TITLE
[BUG] [SM] [ManagementPhase0/Secrets/EncryptionKey] A PolicyStatement used in a resource-based policy must specify at least one IAM principal.

### ISSUE THREAD

**Issue by danieloldberg** [aws-samples/aws-secure-environment-accelerator#991]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.5.1-a
- Install Type: Clean
- Upgrade from version: N/A
- Which State did the Main State Machine Fail in: Phase 0

**Describe the bug**
SM fails at Phase 0 stopping the main SM.
Hard to pinpoint how to solve

**Failure Info**
See Codebuild log below.

**Required files**
Codebuild log:
```
No older events at this moment. Retry
--
[Container] 2022/06/07 11:34:00 Waiting for agent ping
[Container] 2022/06/07 11:34:03 Waiting for DOWNLOAD_SOURCE
[Container] 2022/06/07 11:34:03 Phase is DOWNLOAD_SOURCE
[Container] 2022/06/07 11:34:03 CODEBUILD_SRC_DIR=/codebuild/output/src818249624/src
[Container] 2022/06/07 11:34:03 YAML location is /codebuild/readonly/buildspec.yml
[Container] 2022/06/07 11:34:03 Processing environment variables
[Container] 2022/06/07 11:34:05 Moving to directory /codebuild/output/src818249624/src
[Container] 2022/06/07 11:34:05 Registering with agent
[Container] 2022/06/07 11:34:05 Phases found in YAML: 2
[Container] 2022/06/07 11:34:05  BUILD: 2 commands
[Container] 2022/06/07 11:34:05  POST_BUILD: 2 commands
[Container] 2022/06/07 11:34:05 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
[Container] 2022/06/07 11:34:05 Phase context status code:  Message:
[Container] 2022/06/07 11:34:05 Entering phase INSTALL
[Container] 2022/06/07 11:34:05 Phase complete: INSTALL State: SUCCEEDED
[Container] 2022/06/07 11:34:05 Phase context status code:  Message:
[Container] 2022/06/07 11:34:05 Entering phase PRE_BUILD
[Container] 2022/06/07 11:34:05 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2022/06/07 11:34:05 Phase context status code:  Message:
[Container] 2022/06/07 11:34:05 Entering phase BUILD
[Container] 2022/06/07 11:34:05 Running command cd /app
 
[Container] 2022/06/07 11:34:05 Running command sh docker-entrypoint.sh
The codebuild build type has changed from default to BUILD_GENERAL1_LARGE, increasing the max_old_space_size to 8192
Deploying phase 0...
[AWS codecommit 200 0.261s 0 retries] getFile({
repositoryName: 'ASEA-Config-Repo',
filePath: 'raw/config.json',
commitSpecifier: '85ccaf59e447d1c537eb345f11bdcf5c527d851c'
})
[AWS dynamodb 200 0.059s 0 retries] getItem({ TableName: 'ALZ-Parameters', Key: { id: { S: 'accounts/0' } } })
[AWS dynamodb 200 0.005s 0 retries] getItem({ TableName: 'ALZ-Parameters', Key: { id: { S: 'accounts/1' } } })
[AWS dynamodb 200 0.005s 0 retries] getItem({ TableName: 'ALZ-Parameters', Key: { id: { S: 'limits' } } })
[AWS dynamodb 200 0.025s 0 retries] scan({ TableName: 'ALZ-Outputs' })
[AWS dynamodb 200 0.006s 0 retries] getItem({ TableName: 'ALZ-Parameters', Key: { id: { S: 'organizations' } } })
Skipping creation of Ec2 instance because account-warming-required is false  for account "management"
Skipping creation of Ec2 instance because account-warming-required is false  for account "log-archive"
Skipping creation of Ec2 instance because account-warming-required is false  for account "security"
Skipping creation of Ec2 instance because account-warming-required is false  for account "Operations"
Skipping creation of Ec2 instance because account-warming-required is false  for account "Prod-Perimeter-Account"
Skipping creation of Ec2 instance because account-warming-required is false  for account "Prod-Shared-Services-Account"
Log Bucket not created yet. Continuing.
Total stacks = 12
deploying stack 1 of 12
deploying stack 2 of 12
deploying stack 3 of 12
deploying stack 4 of 12
deploying stack 5 of 12
deploying stack 6 of 12
deploying stack 7 of 12
deploying stack 8 of 12
deploying stack 9 of 12
deploying stack 10 of 12
deploying stack 11 of 12
deploying stack 12 of 12
Error: Validation failed with the following errors:
[ManagementPhase0/Secrets/EncryptionKey] A PolicyStatement used in a resource-based policy must specify at least one IAM principal.
at validateTree (/app/node_modules/.pnpm/@aws-cdk+core@1.144.0/node_modules/@aws-cdk/core/lib/private/synthesis.ts:213:11)
at Object.synthesize (/app/node_modules/.pnpm/@aws-cdk+core@1.144.0/node_modules/@aws-cdk/core/lib/private/synthesis.ts:28:5)
at AccountApp.synth (/app/node_modules/.pnpm/@aws-cdk+core@1.144.0/node_modules/@aws-cdk/core/lib/stage.ts:94:23)
at /app/src/deployments/cdk/toolkit.ts:83:44
at Array.map (<anonymous>)
at Function.create (/app/src/deployments/cdk/toolkit.ts:83:29)
at main (/app/src/deployments/cdk/cdk.ts:104:40)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
 
[Container] 2022/06/07 11:34:10 Command did not exit successfully sh docker-entrypoint.sh exit status 1
[Container] 2022/06/07 11:34:10 Phase complete: BUILD State: FAILED
[Container] 2022/06/07 11:34:10 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sh docker-entrypoint.sh. Reason: exit status 1
[Container] 2022/06/07 11:34:10 Entering phase POST_BUILD
[Container] 2022/06/07 11:34:10 Running command buildComplete=`cat /tmp/buildStatus.txt`
 
[Container] 2022/06/07 11:34:10 Running command if [ $buildComplete = "complete" ]; then echo "Build Finished"; else echo "Build did not finish. please review logs for errors!" && exit 1; fi
Build did not finish. please review logs for errors!
 
[Container] 2022/06/07 11:34:10 Command did not exit successfully if [ $buildComplete = "complete" ]; then echo "Build Finished"; else echo "Build did not finish. please review logs for errors!" && exit 1; fi exit status 1
[Container] 2022/06/07 11:34:10 Phase complete: POST_BUILD State: FAILED
[Container] 2022/06/07 11:34:10 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ $buildComplete = "complete" ]; then echo "Build Finished"; else echo "Build did not finish. please review logs for errors!" && exit 1; fi. Reason: exit status 1
```

**Steps To Reproduce**
1. Install solution
3. Run the SM

**Expected behavior**
Perhaps a more descriptive indicator of what the actual issue is.
Cannot find any good references in config-file for how I could address the issue.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by danieloldberg** [comment]
Solved. IAM settings seem to be required for the management account for this step to pass.
So adding this to the management account got it working again.
```
"iam": {
        "users": [
          {
            "user-ids": [
              "bgUser1",
              "bgUser2"
            ],
            "group": "BreakGlassAdmins",
            "policies": [
              "AdministratorAccess"
            ],
            "boundary-policy": "Default-Boundary-Policy"
          }
        ],
        "policies": [],
        "roles": []
      },
      ```
